export const preloadPack = [
  {src: 'back.jpg', id: 'background'},
  {src: 'sofa.png', id: 'sofa'},
  {src: 'plant_2.png', id: 'plant_2'},
  {src: 'table.png', id: 'table'},
  {src: 'globe.png', id: 'globe'},
  {src: 'char.png', id: 'char'},
  {src: 'icon_hammer.png', id: 'hammer_icon'},
  {src: 'hand.png', id: 'hand'},
  {src: 'old_stair.png', id: 'old_stairs'},
  {src: 'plant.png', id: 'plant'},
  {src: 'ok.png', id: 'ok'},
  {src: 'option_back.png', id: 'option_back'},
  {src: 'option_select.png', id: 'option_select'},
  {src: 'stairs_1_icon.png', id: 'stairs_1_icon'},
  {src: 'stairs_2_icon.png', id: 'stairs_2_icon'},
  {src: 'stairs_3_icon.png', id: 'stairs_3_icon'},
  {src: 'new_stair_01.png', id: 'new_stair_01'},
  {src: 'new_stair_02.png', id: 'new_stair_02'},
  {src: 'new_stair_03.png', id: 'new_stair_03'},
  {src: 'logo.png', id: 'logo'},
  {src: 'btn.png', id: 'btn'},
  {src: 'window.png', id: 'window'},
];
